GET http://localhost:5000/category

# GET http://localhost:5000/gender/1

# POST http://localhost:5000/category
# content-type: application/json

# {
#     "title": "En Promo",
#     "description": "Plein d'articles en promo ..."
# }


# PUT http://localhost:5000/category/1
# content-type: application/json

# {
#     "title": "En Solde"
# }

# PATCH http://localhost:5000/gender/1

# DELETE http://localhost:5000/category/1


