GET http://localhost:5000/gender/1
# GET http://localhost:5000/test

# POST http://localhost:5000/category HTTP/1.1
# content-type: application/json

# {
#     "title": "Promo",
#     "desc": "En promo ..."
# }
